create_basket:
    path: /basket
    methods: [POST]
    defaults:
        _controller: broadway_demo.controller.basket:pickUpBasketAction

add_product:
    path: /basket/{basketId}/addProduct
    methods: [POST]
    defaults:
        _controller: broadway_demo.controller.basket:addProductToBasketAction

remove_product:
    path: /basket/{basketId}/removeProduct
    methods: [POST]
    defaults:
        _controller: broadway_demo.controller.basket:removeProductFromBasketAction

checkout:
    path: /basket/{basketId}/checkout
    methods: [POST]
    defaults:
        _controller: broadway_demo.controller.basket:checkoutAction

get_advice:
    path: /advice/{productId}
    methods: [GET]
    defaults:
        _controller: broadway_demo.controller.people_that_bought_this_product:getAdviceAction
